config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/auth/facebook/callback' => 'sessions#altcreate'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :users do
    resources :trips
  end
  
  resources :cities, only: [:index, :show, :new, :create]
  resources :countries, only: [:index, :show]

  get '/trips/five_star' => 'trips#five_star', as: :five_star


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :trips
  has_many :users, through: :trips
  validates :name, presence: true, uniqueness: true
  validates :country_id, presence: true 

  def country_name=(country_name)
    if country_name[:country] != ""
      country = Country.find_or_create_by(name: country_name[:country])
      self.country_id = country_id
    end
  end

  def rating_avg
    if self.trips.count == 0
      "City has yet to be rated. Please submit your rating to be the first!"
    else
      self.trips.average(:rating).to_f.round(1)
    end
  end

  def combined_name
    "#{self.name}, #{country.name}"
  end

end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  has_many :trips, through: :cities
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user
    belongs_to :city
    validates :city, presence: true
    validates_uniqueness_of :city_id, :scope => :user_id, message: "already added to your trips!"
    validates :rating, presence: true
    validates_numericality_of :rating, :only_integer => true, message: "must be a whole number"
    validates_inclusion_of :rating, :in => 1..5, message: "Please rate using 1 and 5 scale."
    validates :must_visit, presence: true
    validates :comment, presence: true
    scope :five_star, -> { where(rating: 5) }

    def city_attributes=(attributes)
        if attributes[:city] != ""
          city = City.find_or_create_by(name: attributes[:city])
            if attributes[:country] != ""
                country = Country.find_or_create_by(name: attributes[:country])
            else
                country = Country.find_by(id: attributes[:country_id])
            end
          country.cities << city if city != "" && country != ""
          country.save if country != ""
          self.city_id = city.id
        end
    end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips
  has_many :cities, through: :trips
  
  has_secure_password
  validates :name, :email, uniqueness: true
  validates :name, :email, presence: true

  def self.new_from_oauth(auth)
      User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
      u.password = 'password'
      end
  end

  def last_trip
    self.trips.last
  end

  def trip_count
    self.trips.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  helper_method :logged_in?, :current_user, :set_user, :require_login

  def logged_in?
    !!session["user_id"]
  end

  def current_user
    User.find(session["user_id"])
  end

  def set_user
    @user = current_user
  end

  def require_login
    unless logged_in? 
        flash[:error] = "Please login to continue."
        redirect_to login_path
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
    before_action :require_login

    def index
        if params[:q]
            @cities = City.where("name like ?", "%#{params[:q]}%")
            #byebug
        else
            @cities = City.all
        end

    end

    def show
        @city = City.find(params[:id])
    end

    def new 
        @city = City.new
    end

    def create
        @city = City.create(city_params)
        if @city.save
            redirect_to cities_path(@city), :flash => { :success => "City has been succesfully added!"}
        else 
            render :new
        end
    end

    private 

    def city_params
        params.require(:city).permit(:name, :country_id, country_name:[:country])
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :require_login
    
    def index
        @countries = Country.all
    end

    def show
        @country = Country.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def altcreate
        @user = User.new_from_oauth(auth)
        session[:user_id] = @user.id
        redirect_to users_path, :notice => "Signed in!"
    end

     def create
         @user = User.find_by(email: params[:user][:email])
         if @user && @user.authenticate(params[:user][:password])
             session[:user_id] = @user.id
             redirect_to users_path
         else
            
             redirect_to login_path, :flash => { :error => "Incorrect username/password. Please try again."}
         end
    end

    def destroy
        session.destroy
        redirect_to root_path, :notice => "Sucessfully Logged Out!"
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_login 

  def index
    find_user    
    @trips = @user.trips.all
  end

  def show
    find_user 
    find_trip
  end

  def new
    set_user
    find_city
    @trip = Trip.new
  end

  def create
    set_user
    find_city    
    @trip = @user.trips.build(trip_params)
    if @trip.save
        redirect_to user_trips_path(@user), :flash => { :success => "Trip successfully added!"}
    else
        render :new
    end
  end

  def edit
    set_user
    find_trip
    if @trip.user != current_user
        redirect_to user_trips_path(@user), :flash => { :error => "Trip belongs to another user. Unable to edit."}
    end
  end

  def update
    set_user
    find_trip
    if @trip.update(trip_params)
        redirect_to user_trips_path(@user), :flash => { :success => "Trip successfully updated!"}
    else
        render :edit
    end
  end

  def five_star
    set_user
  end

  def destroy
    set_user
    find_trip
    @trip.destroy
    redirect_to user_trips_path(@user), :flash => { :success => "Trip has been deleted!"}
  end

  private

  def trip_params
    params.require(:trip).permit(:user_id, :city_id, :rating, :must_visit, :comment, city_attributes:[:city, :country, :country_id])
  end

  def find_trip
    @trip = Trip.find(params[:id])
  end

  def find_city
    @city = City.find_by(id: params[:city_id])
  end

  def find_user
    @user = User.find_by(id: params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :require_login 

    def index
        @users = User.all
    end

    def show
        set_user
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user), :flash => { :success => "Welcome, #{@user.name}! Your account was successfully created."}
        else
            render :new
        end
    end


    private

    def user_params
        params.require(:user).permit(:email, :name, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def flash_class(level)
        case level
          when 'notice' then "alert alert-info"
          when 'success' then "alert alert-success"
          when 'error' then "alert alert-danger"
          when 'alert' then "alert alert-warning"
        end
      end
      
end

app/views/cities/index.html.erb
<h2 class="align-table">Explore Cities</h2>
<%= form_with(url: "/cities", method: "get", local: true) do %>
  <%= label_tag(:q, "Search for City Name:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Average Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
    <tr class="border-bottom">
      <td class="no-underline"><%= link_to city.combined_name, city_path(city) %></td>
      <td><%= city.rating_avg %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/cities/new.html.erb
<div class="form">
  <h3>Add New City</h3><br>

  <%= form_for @city do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :country, "Select Country" %>
    <%= f.collection_select :country_id, Country.order('name ASC'), :id, :name, :include_blank => true %>

    <%= f.fields_for :country_name do |ctry_name| %>
      <%= f.label :country, "Or Add New Country" %>
      <%= ctry_name.text_field :country %><br><br>
      <% end %>

    <div class="form-errors">
      <% if @city.errors.any? %>
        <div id="error_explanation">
          <p><%= pluralize(@city.errors.count, "error") %> prohibited this city from being created:</p>
          <ul>
            <% @city.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <%= f.submit "Add City", :class => 'btn btn-sm btn-success' %>
  <% end %>
</div>

app/views/cities/show.html.erb
<div class="list-details">
  <h4><%= @city.combined_name %></h4>
  <span class="bold-text">Average Rating: </span><%= @city.rating_avg %><br>
  <p><span class="bold-text">Total Reviews: </span><%= @city.trips.count %></p>

  <% @city.trips.each do |trip| %>
    <div class="underlined-list">
      <%= trip.comment %>
      <p>- <%= trip.user.name %> (<%= trip.rating %> stars)</p>
    </div>
  <% end %>

  <% if !Trip.exists?(user_id: current_user.id, city_id: @city.id) %>
    <%= link_to "Been to #{@city.name}? Add it to your trips!", new_user_trip_path(:user_id => current_user.id, :city_id => @city.id) %>
  <% end %>
</div>

app/views/countries/index.html.erb
<h4 class="align-table">Explore Countries</h4>
<table>
  <thead>
    <tr>
      <th>Country</th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
    <tr class="border-bottom">
      <td class="no-underline"><%= link_to country.name, country_path(country) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/countries/show.html.erb
<div class="list-details">
  <h4><%= @country.name %></h4>
  <p>Read reviews of <%= pluralize(@country.cities.count, "city") %> from <%= pluralize(@country.trips.count, "traveler") %></p>
    <% @country.cities.each do |city| %>
    <div class="underlined-list">
      <p class="no-underline bold-text"><%= link_to city.name, city_path(city) %></p>
      <%= pluralize(city.users.count, "traveler") %><br>
      <% if !city.users.empty? %>
        <p>Last reviewed by <%= city.users.last.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBuddies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if session["user_id"] %> 
        <a href="/users"> Home</a><br>
        <a href="/users/:id"> User Profile</a><br>
        <a href="/cities/new"> Add New City</a><br>
        <a href="/cities"> Explore Cities</a><br>
        <a href="/countries"> Explore Countries</a><br>
        <a href= "/logout"> Logout </a>
      <% else %>
        <a href= "/signup"> Sign-Up </a><br>
        <a href= "/login"> Login </a>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= f.hidden_field :user_id, value: @user.id %>

<%= f.label :rating, "Rating (Scale of 1-5)" %>
<%= f.text_field :rating %><br><br>

<%= f.label :must_visit, "Must Visit" %>
<%= f.text_field :must_visit %><br><br>

<%= f.label :comment, "Share Additional Details" %><br><br>
<%= f.text_area :comment, :size => "35x5" %><br><br>

<div class="form-errors">
<% if @trip.errors.any? %>
<div id="error_explanation">
  <p><%= pluralize(@trip.errors.count, "error") %> occurred:</p>
  <ul>
    <% @trip.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
</div>
© 2020 GitHub, Inc.

app/views/trips/edit.html.erb
<div class="form">
  <h3>Edit Trip</h3><br>
    <%= form_for :trip, url: user_trip_path, :method => 'patch' do |f| %>
      <%= f.hidden_field :city_id %>
      <%= f.label :city %>
      <%= f.text_field :city, value: @trip.city.name, readonly: true %><br><br>
      <%= render partial: 'form', locals: { f: f} %>
      <%= f.submit "Update Trip", :class => 'btn btn-sm btn-success auto' %>
    <% end %>
</div>

app/views/trips/five_star.html.erb
<h4 class="blue-bold">Trips Rated 5 Stars by <%= @user.name %>:</h4><br>
  <% if @user.trips.five_star.count >= 1 %>
    <% @user.trips.five_star.each do |trip| %>
      <p class="no-underline"><%= link_to trip.city.combined_name, user_trip_path(@user, trip) %></p>
    <% end %>
    <% else %>
    <p>You don't have any 5-star trips yet.</p>
  <% end %>
<span class="blue-bold"><%= link_to "<-- Return to My Profile", user_path(@user) %></span>

app/views/trips/index.html.erb
<h4 class="align-table"><%= @user.name %>'s Trips</h4>
<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Must See Attraction</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
    <tr class="border-bottom">
      <td class="no-underline"><%= link_to trip.city.name, user_trip_path(@user, trip) %></td>
      <td><%= trip.must_visit %></td>
      <% if @user == current_user %>
        <td><%= link_to "Edit Trip", edit_user_trip_url(@user, trip), :method => 'get' %></td>
      <% else %>
        <td> </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<div class="button-below-table">
  <% if @user == current_user %>
    <%= link_to "Add New Trip", new_user_trip_url(@user), :class => 'btn btn-sm btn-primary btn-rounded' %>
  <% end %><br><br>
  <span class="blue-bold"><%= link_to "<-- Return to My Profile", user_path(@user) %></span>
</div>

app/views/trips/new.html.erb
<h3>Add New Trip</h3><br>
    <%= form_for :trip, url: user_trips_path do |f| %>
      <% if @city %>
        <%= f.hidden_field :city_id, value: @city.id %>
        <%= f.label :city %>
        <%= f.text_field :city, value: @city.name, readonly: true %><br><br>
      <% else %>
        <%= f.label :city, "Select City" %>
        <%= f.collection_select :city_id, City.order('name ASC'), :id, :combined_name, :include_blank => true %><br>
        <p>* OR add a new city by entering details below:</p>
        <%= f.fields_for :city_attributes do |city_attr| %>
          <%= f.label :city, "City Name" %>
          <%= city_attr.text_field :city %>
          <%= f.label :country, "Select Country" %>
          <%= city_attr.collection_select :country_id, Country.order('name ASC'), :id, :name, :include_blank => true %>
          <%= f.label :country, "Add New Country" %>
          <%= city_attr.text_field :country %><br><br>
      <% end %>
    <% end %>
    <%= render partial: 'form', locals: { f: f} %>
    <%= f.submit "Add Trip", :class => 'btn btn-sm btn-success' %>
  <% end %>

app/views/trips/show.html.erb
<div class="info-box med-box">
  <h4 class="box-heading"><%= @user.name %>'s <%= @trip.city.name %> Trip</h4>
  <p><span class="bold-text">Rating: </span><%= @trip.rating %></p>
  <p><span class="bold-text">Must Visit: </span><%= @trip.must_visit %></p>
  <p><span class="bold-text">Review: </span><%= @trip.comment %></p><br>

  <% if @user == current_user %>
    <%= link_to "Edit Trip", edit_user_trip_url, :class => 'btn btn-sm btn-primary btn-rounded' %>
    <%= link_to "Delete Trip", user_trip_path, :method => 'delete', data: { confirm: "Are you sure?" }, :class => 'btn btn-sm btn-secondary btn-rounded' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 <strong style="color: green;"> Welcome to Travel Buddies!</h1>
<h4>Explore the Travels of the Travel Buddies:</h4>
  <% @users.each do |user| %>
    <div class="underlined-list">
      <span class="no-underline bold-text"><%= link_to user.name, user_trips_path(user) %> </span><br>
      <% if user.trips.count >= 1 %>
        <p>Last Trip Added: <%= user.last_trip.city.name %></p>
        <% else%>
        <p>No trips added yet</p>
      <% end %>
    </div>
  <% end %>

app/views/users/new.html.erb
<h2 <strong style="color: green;"> Create a Travel Buddies Account</strong></h2><br>
<%= form_for @user do |f| %>
    <%= f.text_field :email, placeholder: "Email", :size => 30 %>
    <%= f.text_field :name, placeholder: "Username", :size => 30 %>
    <%= f.password_field :password, placeholder: "Password", :size => 30 %><br><br>
    <%= f.submit "Create Account", :class => 'btn btn-block btn-success' %>
<% end %>

<% if @user.errors.any? %>
        <div id="error_explanation">
            <p><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
<% end %>

app/views/users/show.html.erb
<h4 class="box-heading"><%= @user.name %></h4>
<img src="<%= @user.image %>">
  <% if @user.trips.count == 0 %>
    <p>You haven't added any trips yet.</p><br>
  <% else %>
    <p>You've added <%= pluralize(@user.trip_count, "trip") %>.</p>
    <span class="bold-text">Last Trip Added:</span>
    <span class="no-underline"><%= link_to @user.last_trip.city.name, user_trip_path(@user, @user.last_trip) %></span><br><br>
    <%= link_to "View My 5-Star Trips", five_star_path %><br><br>
    <%= link_to "See All My Trips", user_trips_path(@user) %><br>
  <% end %>
  <%= link_to "Add a New Trip", new_user_trip_url(@user) %>

app/views/welcome/home.html.erb
<div class="home">
  <h1 <strong style="color: green;">Welcome to Travel Buddies!</h1><br>
</div>